"""create todo table, updated_at and created_at

Revision ID: b580d7c731e7
Revises: d3e46e979648
Create Date: 2026-01-26 22:08:54.288518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b580d7c731e7'
down_revision: Union[str, Sequence[str], None] = 'd3e46e979648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('todos', schema=None) as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('todos', schema=None) as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        # ### end Alembic commands ###
